
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        APP_PORT: ${APP_PORT}
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:alpine
    networks:
      - app-network
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - ${PWD}/redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongodb:
    image: mongo:latest
    networks:
      - app-network
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.stats()"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:

volumes:
  redis-data:
  mongo-data:
